version: "3"
services:
  your_ip:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/app/
#    ports:
#      - "8899:8000"
    depends_on:
      - psql
    command: [ "./wait-for-it.sh", "psql:5432", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000" ]

  psql:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=iie
      - POSTGRES_PASSWORD=bCYI636wkDFX
      - POSTGRES_DB=ctf



  nginx:
    image: nginx:1.15
    ports:
      - "8029:80"
    volumes:
      - ./conf/example.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - your_ip